/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author Abid-Temp
 */
public class EditPanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form EditPanel
     */
    public EditPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        editB = new GUI.RectangularButton();
        closeB = new GUI.RectangularButton();
        deleteB = new GUI.RectangularButton();
        editL = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(648, 96));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        editB.setBorder(null);
        editB.setPreferredSize(new java.awt.Dimension(141, 43));
        add(editB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 27, -1, -1));

        closeB.setBorder(null);
        closeB.setPreferredSize(new java.awt.Dimension(141, 43));
        add(closeB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 27, -1, -1));
        
        deleteB.setBorder(null);
        deleteB.setPreferredSize(new java.awt.Dimension(141, 43));
        add(deleteB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 27, -1, -1));

        editL.setIcon(new javax.swing.ImageIcon(GUI._GUIGlobals.directory + "\\Raw Materials\\Templates\\function_buttons\\Slide1.JPG")); // NOI18N
        editL.setPreferredSize(new java.awt.Dimension(648, 96));
        add(editL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel editL;
    private GUI.RectangularButton editB;
    private GUI.RectangularButton closeB;
    private GUI.RectangularButton deleteB;
    // End of variables declaration//GEN-END:variables
}
