/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.event.ActionEvent;

import javax.swing.JFrame;

/**
 *
 * @author Abid-Temp
 */
public class Notification extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String message;

	/**
	 * Creates new form AddPanel
	 */
	public Notification(String message) {
		this.message = message;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		okL = new javax.swing.JLabel();
		messageTA = new javax.swing.JTextArea();
		okB = new GUI.RectangularButton();

		setPreferredSize(new java.awt.Dimension(491, 271));
		setUndecorated(true);
		requestFocus();
		setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

		messageTA.setPreferredSize(new java.awt.Dimension(360, 125));
		messageTA.setBorder(null);
		messageTA.setBackground(new java.awt.Color(13, 13, 13));
		messageTA.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
		messageTA.setForeground(GUI._GUIGlobals.fontColor);
		messageTA.setLineWrap(true);
		messageTA.setWrapStyleWord(true);
		messageTA.setBorder(null);
		messageTA.setEditable(false);
		messageTA.setText(message);
		getContentPane().add(messageTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 67, -1, -1));

		okB.setBorder(null);
		okB.setPreferredSize(new java.awt.Dimension(141, 43));
		okB.addActionListener(new java.awt.event.ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				dispose();
			}

		});
		add(okB, new org.netbeans.lib.awtextra.AbsoluteConstraints(336, 211, -1, -1));

		okL.setIcon(
				new javax.swing.ImageIcon(GUI._GUIGlobals.directory + "\\Raw Materials\\Templates\\notification.JPG"));
		okL.setPreferredSize(new java.awt.Dimension(491, 271));
		okL.setBorder(javax.swing.BorderFactory.createLineBorder(GUI._GUIGlobals.fontColor));
		getContentPane().add(okL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

		pack();
		setLocationRelativeTo(null);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
		setVisible(true);
	}// </editor-fold>//GEN-END:initComponents

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel okL;
	private javax.swing.JTextArea messageTA;
	private GUI.RectangularButton okB;
	// End of variables declaration//GEN-END:variables
}
