/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

import Facade.Functions;
import GUI.RectangularButton;
import GUI._GUIGlobals;

/**
 *
 * @author Abid-Temp
 */
public class PurchaseDetails extends JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private int transportTransactionNo;

	private JLabel backgroundL;
	private JPanel functionP;
	private JComboBox<String> transportTransactionNoCB;
	private JLayeredPane functionsLP;
	private JCheckBox isTransportCB;
	private RectangularButton addTransportB;

	public void setBackground(JLabel background) {
		BufferedImage img = null;
		try {
			img = ImageIO
					.read(new File(_GUIGlobals.directory + "\\Raw Materials\\Templates\\localpurchase\\Slide2.jpg"));
		} catch (IOException e) {
			e.printStackTrace();
		}
		Image dimg = img.getScaledInstance(_GUIGlobals.frameWidth, _GUIGlobals.frameHeight, Image.SCALE_SMOOTH);
		ImageIcon imageIcon = new ImageIcon(dimg);
		background.setIcon(imageIcon);
	}

	public JLabel getBackgroundL() {
		return backgroundL;
	}

	public JPanel getFunctionP() {
		return functionP;
	}

	public JLayeredPane getFunctionsLP() {
		return functionsLP;
	}

	public JComboBox<String> getTransportTransactionNoCB() {
		return transportTransactionNoCB;
	}

	public JCheckBox getIsTransportCB() {
		return isTransportCB;
	}

	public RectangularButton getAddTransportB() {
		return addTransportB;
	}

	public int getTransportTransactionNo() {
		return transportTransactionNo;
	}

	public void setTransportTransactionNo(int transportTransactionNo) {
		this.transportTransactionNo = transportTransactionNo;
	}

	public void setBackgroundL(JLabel backgroundL) {
		this.backgroundL = backgroundL;
	}

	public void setFunctionP(JPanel functionP) {
		this.functionP = functionP;
	}

	public void setTransportTransactionNoCB(JComboBox<String> transportTransactionNoCB) {
		this.transportTransactionNoCB = transportTransactionNoCB;
	}

	public void setFunctionsLP(JLayeredPane functionsLP) {
		this.functionsLP = functionsLP;
	}

	public void setIsTransportCB(JCheckBox isTransportCB) {
		this.isTransportCB = isTransportCB;
	}

	public void setAddTransportB(RectangularButton addTransportB) {
		this.addTransportB = addTransportB;
	}

	public Dimension getTransportTransactionNoCBSize() {
		double wfactor = 10.37837838;
		double hfactor = 32.72727273;
		return (new Dimension((int) (_GUIGlobals.screenWidth / wfactor), (int) (_GUIGlobals.screenHeight / hfactor)));
	}

	public Dimension getTransportTransactionNoCBPos() {
		double wfactor = 12.1575985;
		double hfactor = 15.84507042;
		return (new Dimension((int) (_GUIGlobals.screenWidth / wfactor), (int) (_GUIGlobals.screenHeight / hfactor)));
	}

	public Dimension getIsTransportCBPos() {
		double wfactor = 39.87692308;
		double hfactor = 33.08823529;
		return (new Dimension((int) (_GUIGlobals.screenWidth / wfactor), (int) (_GUIGlobals.screenHeight / hfactor)));
	}

	public Dimension getAddTransportBSize() {
		double wfactor = 23.45701357;
		double hfactor = 26.78571429;
		return (new Dimension((int) (_GUIGlobals.screenWidth / wfactor), (int) (_GUIGlobals.screenHeight / hfactor)));
	}

	public Dimension getAddTransportBPos() {
		double wfactor = 5.345432048;
		double hfactor = 16.30434783;
		return (new Dimension((int) (_GUIGlobals.screenWidth / wfactor), (int) (_GUIGlobals.screenHeight / hfactor)));
	}

	public void setEditable(boolean isEnabled) {
		getTransportTransactionNoCB().setEnabled(isEnabled);
		getIsTransportCB().setEnabled(isEnabled);
		getAddTransportB().setEnabled(isEnabled);
	}

	/**
	 * Creates new form Transaction
	 */
	public PurchaseDetails(JPanel panel) {
		functionP = panel;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */

	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		functionsLP = new JLayeredPane();
		backgroundL = new JLabel();
		transportTransactionNoCB = new JComboBox<>();
		addTransportB = new RectangularButton();
		isTransportCB = new JCheckBox();
		transportTransactionNo = ((Frame.Purchase) Functions.getTempObj()).getTransportTransactionNo();

		setUndecorated(true);
		setPreferredSize(new Dimension(_GUIGlobals.frameWidth, _GUIGlobals.frameHeight));
		requestFocus();
		getContentPane().setLayout(new AbsoluteLayout());

		functionsLP.setBackground(new Color(13, 13, 13));
		functionsLP.setForeground(_GUIGlobals.fontColor);
		functionsLP.setLayout(new AbsoluteLayout());
		functionsLP.add(functionP, new AbsoluteConstraints(0, 0, -1, -1));
		getContentPane().add(functionsLP, new AbsoluteConstraints(Transaction.getFunctionsLPPos().width,
				Transaction.getFunctionsLPPos().height, -1, -1));

		transportTransactionNoCB.setBackground(_GUIGlobals.fontColor);
		transportTransactionNoCB.setForeground(_GUIGlobals.fontColor);
		transportTransactionNoCB.setFont(new Font("Century Gothic", 0, _GUIGlobals.getFontSize_18()));
		transportTransactionNoCB.setModel(new DefaultComboBoxModel<>(new String[] { "" }));
		transportTransactionNoCB.setBorder(null);
		transportTransactionNoCB.setPreferredSize(
				new Dimension(getTransportTransactionNoCBSize().width, getTransportTransactionNoCBSize().height));
		transportTransactionNoCB.setEnabled(false);
		transportTransactionNoCB.addActionListener(new ActionListener() {

			@SuppressWarnings("unchecked")
			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				String transportString = (String) ((JComboBox<String>) arg0.getSource()).getSelectedItem();
				if (transportString != null)
					if (!transportString.equals(""))
						transportTransactionNo = Integer.parseInt(transportString);
			}

		});
		getContentPane().add(transportTransactionNoCB, new AbsoluteConstraints(getTransportTransactionNoCBPos().width,
				getTransportTransactionNoCBPos().height, -1, -1));

		isTransportCB.setForeground(_GUIGlobals.fontColor);
		isTransportCB.setBorder(null);
		isTransportCB.setSelected(false);
		isTransportCB.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent evt) {
				if (((JCheckBox) evt.getSource()).isSelected()) {
					transportTransactionNoCB.setEnabled(true);
					addTransportB.setEnabled(true);
				} else {
					transportTransactionNoCB.setSelectedIndex(-1);
					transportTransactionNoCB.setEnabled(false);
					addTransportB.setEnabled(false);
				}
			}
		});
		getContentPane().add(isTransportCB,
				new AbsoluteConstraints(getIsTransportCBPos().width, getIsTransportCBPos().height, -1, -1));

		addTransportB.setEnabled(false);
		addTransportB.setBorder(null);
		addTransportB.setPreferredSize(new Dimension(getAddTransportBSize().width, getAddTransportBSize().height));
		addTransportB.addActionListener(new ActionListener() {

			@Override
			public void actionPerformed(ActionEvent arg0) {
				// TODO Auto-generated method stub
				Functions.create("ADD TRANSPORT DETAILS 2");
			}

		});
		getContentPane().add(addTransportB,
				new AbsoluteConstraints(getAddTransportBPos().width, getAddTransportBPos().height, -1, -1));

		setBackground(backgroundL);
		backgroundL.setBorder(BorderFactory.createLineBorder(_GUIGlobals.fontColor));
		backgroundL.setPreferredSize(new Dimension(_GUIGlobals.frameWidth, _GUIGlobals.frameHeight));
		getContentPane().add(backgroundL, new AbsoluteConstraints(0, 0, -1, -1));

		pack();
		setLocationRelativeTo(null);
		setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}// </editor-fold>//GEN-END:initComponents
}
