/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

/**
 *
 * @author Abid-Temp
 */
public class UpdatePanel extends javax.swing.JPanel {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form UpdatePanel
     */
    public UpdatePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        updateB = new GUI.RectangularButton();
        cancelB = new GUI.RectangularButton();
        updateL = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(648, 96));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        updateB.setBorder(null);
        updateB.setPreferredSize(new java.awt.Dimension(141, 43));
        add(updateB, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 27, -1, -1));

        cancelB.setBorder(null);
        cancelB.setPreferredSize(new java.awt.Dimension(141, 43));
        add(cancelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(497, 27, -1, -1));

        updateL.setIcon(new javax.swing.ImageIcon(GUI._GUIGlobals.directory + "\\Raw Materials\\Templates\\function_buttons\\Slide2.JPG")); // NOI18N
        updateL.setPreferredSize(new java.awt.Dimension(648, 96));
        add(updateL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel updateL;
    private GUI.RectangularButton updateB;
    private GUI.RectangularButton cancelB;
    // End of variables declaration//GEN-END:variables
}
